### ISSUE TITLE
Initialize data does not respect environment variables

### ISSUE THREAD

**Issue by nickdbush** [superdesk/superdesk-core#1731]
Running the ```app:initialize_data``` command from ```manage.py``` throws an error:

```pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused```

It seems to not respect the ```MONGO_URI``` env variable from within a Docker container. Some commands seem to respect the variable (such as ```users:create```).

**Comment by cendekia** [comment]
I'm facing this issue right now, I did install superdesk using `docker-compose up -d`
then I run this command to initialize elastic/mongo
`docker-compose run superdesk-server run python manage.py app:initialize_data`

But I am facing these errors:
```
INFO:superdesk:Uhoh, an exception occured while running the command...
ERROR:superdesk:localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 605a080e0d1101632ef31292, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>
Traceback (most recent call last):
  File "/opt/superdesk/src/superdesk-core/superdesk/__init__.py", line 56, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/superdesk/src/superdesk-core/apps/prepopulate/app_initialize.py", line 279, in run
    app.init_indexes(ignore_duplicate_keys=True)
  File "/opt/superdesk/src/superdesk-core/superdesk/factory/app.py", line 101, in init_indexes
    create_index(self, resource, name, list_of_keys, index_options)
  File "/usr/local/lib/python3.6/site-packages/eve/io/mongo/mongo.py", line 1172, in _create_index
    coll.create_index(list_of_keys, **kw)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 2059, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 1919, in __create_indexes
    with self._socket_for_writes(session) as sock_info:
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 198, in _socket_for_writes
    return self.__database.client._socket_for_writes(session)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1293, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 243, in select_server
    address))
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 200, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 605a080e0d1101632ef31292, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>
```

**Comment by nickdbush** [comment]
Hi @cendekia, I'm running into these issues with the new Docker containers as well, which is unexpected. Would appreciate any insight that you've gathered as we continue to track down the source of this issue.

**Comment by gmaruti** [comment]
Facing same issue. Appreciate help in addressing the issue

**Comment by nickdbush** [comment]
It seems that part of the init process isn't respecting the mongo environment config, which is a regression against our beta containers that were available. I'm pretty sure that the containers are built from the `demo` branch, although this means we should probably be trying to build the `:latest` tag from `master`. If anyone has any Docker knowledge I would appreciate another set of eyes on the `demo` Dockerfiles!

**Comment by nickdbush** [comment]
The images under [/u/sourcefabricoss](https://hub.docker.com/u/sourcefabricoss) on Docker Hub have been updated with a fix for this issue. Let me know how it goes @cendekia and @gmaruti
